### ISSUE TITLE
No button appears

### ISSUE THREAD

**Issue by Mile140** [John-nata/YT-Playlist-Cleaner#1]
Hello- i tried this on Chrome and Edge but no button is appearing.  (Windows 11)  In Edge, it shows the script ran, but no button is appearing that I can see.

**Comment by Mile140** [comment]
Never mind- i noticed at the very bottom of the code when I pasted into TamperMOnkey was line that said Save to Cacher, which was causing an error- removed that line and it works !

**Comment by John-nata** [comment]
Thank you for reporting this issue. I've recently updated the script, which should resolve the problems you've encountered. 

- Removed "Save to Cacher" line:
 The line causing an error at the bottom of the script has been removed. This was likely an artifact from a previous version or development environment and is not needed for the script's functionality. Sorry for that.
 
- "Nothing happens when I start deleting":
 I've improved the script's initialization and UI creation process. The script should now properly create a floating UI with all necessary controls when you load a YouTube playlist page. If you're still not seeing any action when clicking the "Start Deleting" button, please make sure you're on a YouTube playlist page and that the script has fully loaded.
 
- Storage Access Permission Denied:
 The updated version of the script no longer relies on storage access. All calls to requestStorageAccessFor have been removed, which were causing the permission denied errors you saw in the console. The script now uses in-memory configuration that's updated based on the values you input in the UI. This means you should no longer see any storage-related errors in the console.

To use the updated script:
- Remove the old version of the script from Tampermonkey.
- Install the new version of the script.
- Reload any open YouTube playlist pages.
- You should see a floating UI appear on YouTube playlist pages with options to configure and start the cleaner.

If you're still experiencing issues after installing the updated script, please let me know :)
